name: Weekly Task Rotation

on:
  schedule:
    - cron: '0 9 * * 1' # co poniedziałek o 9:00 UTC
  workflow_dispatch:     # można też uruchomić ręcznie

jobs:
  assign-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy smtplib email-validator

      - name: Run assignment script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python .github/scripts/assign_tasks.py
